# Generated by Django 5.2 on 2025-05-05 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolum_kodu', models.CharField(max_length=10, unique=True, verbose_name='Bölüm Kodu')),
                ('bolum_adi', models.CharField(max_length=100, verbose_name='Bölüm Adı')),
            ],
        ),
        migrations.CreateModel(
            name='Derslik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derslik_adi', models.CharField(max_length=50, unique=True, verbose_name='Derslik Adı')),
                ('kapasite', models.PositiveIntegerField(verbose_name='Kapasite')),
                ('statu', models.CharField(choices=[('NORMAL', 'Normal'), ('LAB', 'Laboratuvar')], default='NORMAL', max_length=10, verbose_name='Statü')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalKisiti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aciklama', models.CharField(blank=True, help_text='Örn: Öğle Arası, Fakülte Toplantısı', max_length=200)),
                ('gun', models.CharField(choices=[('Pazartesi', 'Pazartesi'), ('Salı', 'Salı'), ('Çarşamba', 'Çarşamba'), ('Perşembe', 'Perşembe'), ('Cuma', 'Cuma')], max_length=10, verbose_name='Gün')),
                ('baslangic_saati', models.TimeField(verbose_name='Uygun Olmayan Başlangıç Saati')),
                ('bitis_saati', models.TimeField(verbose_name='Uygun Olmayan Bitiş Saati')),
            ],
            options={
                'verbose_name': 'Genel Kısıtlama',
                'verbose_name_plural': 'Genel Kısıtlamalar',
                'unique_together': {('gun', 'baslangic_saati')},
            },
        ),
        migrations.CreateModel(
            name='Ogrenci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogrenci_no', models.CharField(max_length=20, unique=True, verbose_name='Öğrenci Numarası')),
                ('ad_soyad', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('sinif', models.IntegerField(verbose_name='Sınıf')),
                ('bolum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.bolum', verbose_name='Bölümü')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Hesabı')),
            ],
        ),
        migrations.CreateModel(
            name='OgretimUyesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Hesabı')),
            ],
        ),
        migrations.CreateModel(
            name='Ders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ders_kodu', models.CharField(max_length=10, unique=True, verbose_name='Ders Kodu')),
                ('ders_adi', models.CharField(max_length=100, verbose_name='Ders Adı')),
                ('sinif', models.IntegerField(verbose_name='Sınıf')),
                ('haftalik_saat', models.PositiveIntegerField(verbose_name='Haftalık Ders Saati')),
                ('tip', models.CharField(choices=[('TEORIK', 'Teorik'), ('LAB', 'Laboratuvar'), ('UYGULAMA', 'Uygulama')], default='TEORIK', max_length=10, verbose_name='Ders Tipi (Yapısal)')),
                ('kontenjan', models.PositiveIntegerField(default=50, verbose_name='Kontenjan')),
                ('zorunlu_saat_gun', models.CharField(blank=True, max_length=10, null=True, verbose_name='Zorunlu Gün')),
                ('zorunlu_baslangic_saati', models.TimeField(blank=True, null=True, verbose_name='Zorunlu Başlangıç Saati')),
                ('is_zorunlu', models.BooleanField(default=True, verbose_name='Zorunlu Ders mi?')),
                ('kredi', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Kredi')),
                ('akts', models.IntegerField(blank=True, null=True, verbose_name='AKTS')),
                ('donem', models.IntegerField(blank=True, null=True, verbose_name='Dönem (1-8)')),
                ('is_shared', models.BooleanField(default=False, verbose_name='Ortak Ders mi?')),
                ('is_online', models.BooleanField(default=False, verbose_name='Online Ders mi?')),
                ('bolum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dersler', to='schedule.bolum', verbose_name='Bölümü')),
                ('ogretim_uyeleri', models.ManyToManyField(blank=True, related_name='verdigi_dersler', to='schedule.ogretimuyesi', verbose_name='Öğretim Üyeleri')),
            ],
        ),
        migrations.CreateModel(
            name='DersProgramiSlotu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun', models.CharField(choices=[('Pazartesi', 'Pazartesi'), ('Salı', 'Salı'), ('Çarşamba', 'Çarşamba'), ('Perşembe', 'Perşembe'), ('Cuma', 'Cuma')], max_length=10, verbose_name='Gün')),
                ('baslangic_saati', models.TimeField(verbose_name='Başlangıç Saati')),
                ('bitis_saati', models.TimeField(verbose_name='Bitiş Saati')),
                ('sinif', models.IntegerField(verbose_name='Sınıf')),
                ('academic_year', models.CharField(max_length=10, verbose_name='Akademik Yıl')),
                ('semester', models.CharField(max_length=10, verbose_name='Dönem (Güz/Bahar)')),
                ('is_manually_adjusted', models.BooleanField(default=False, verbose_name='Manuel Ayarlandı mı?')),
                ('bolum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.bolum', verbose_name='Bölüm')),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.ders', verbose_name='Ders')),
                ('derslik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.derslik', verbose_name='Derslik')),
                ('ogretim_uyesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.ogretimuyesi', verbose_name='Öğretim Üyesi')),
            ],
            options={
                'verbose_name_plural': 'Ders Programı Slotları',
                'unique_together': {('bolum', 'sinif', 'gun', 'baslangic_saati'), ('derslik', 'gun', 'baslangic_saati'), ('ogretim_uyesi', 'gun', 'baslangic_saati')},
            },
        ),
        migrations.CreateModel(
            name='OgretimUyesiKisiti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun', models.CharField(choices=[('Pazartesi', 'Pazartesi'), ('Salı', 'Salı'), ('Çarşamba', 'Çarşamba'), ('Perşembe', 'Perşembe'), ('Cuma', 'Cuma')], max_length=10, verbose_name='Gün')),
                ('baslangic_saati', models.TimeField(verbose_name='Uygun Olmayan Başlangıç Saati')),
                ('bitis_saati', models.TimeField(verbose_name='Uygun Olmayan Bitiş Saati')),
                ('ogretim_uyesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kisitlari', to='schedule.ogretimuyesi', verbose_name='Öğretim Üyesi')),
            ],
            options={
                'verbose_name_plural': 'Öğretim Üyesi Kısıtları',
                'unique_together': {('ogretim_uyesi', 'gun', 'baslangic_saati')},
            },
        ),
    ]
