# Generated by Django 5.2 on 2025-05-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ders',
            name='ders_kodu',
            field=models.CharField(max_length=10, verbose_name='Ders Kodu'),
        ),
    ]
